import 'package:taptapdoner/domain/upgrades/upgrade_models.dart';

class UpgradeDefinitions {
  const UpgradeDefinitions._();

  static const List<UpgradeTrack> tracks = [
    UpgradeTrack(
      id: 'knife',
      title: 'Bicak',
      description: 'Tap basina doner kesim gucunu artirir.',
      type: UpgradeTrackType.knife,
      effectType: UpgradeEffectType.tapMultiplier,
      itemIndex: 0,
      level: 1,
      tiers: [
        UpgradeItemTier(
          id: 'rusty_knife',
          name: 'Pasli Bicak',
          description: 'Baslangic bicagi.',
          iconKey: 'rusty_knife',
          tier: 1,
          iconPath: 'assets/ui/upgrades/knife/rusty_knife.png',
          baseCost: 20,
          costMultiplier: 1.22,
          baseEffect: 1.00,
          levelEffect: 0.08,
        ),
        UpgradeItemTier(
          id: 'sharp_knife',
          name: 'Keskin Bicak',
          description: 'Ilk ciddi kesim gelisimi.',
          iconKey: 'sharp_knife',
          tier: 2,
          iconPath: 'assets/ui/upgrades/knife/sharp_knife.png',
          baseCost: 600,
          costMultiplier: 1.23,
          baseEffect: 3.20,
          levelEffect: 0.16,
        ),
        UpgradeItemTier(
          id: 'double_knife',
          name: 'Cift Bicak',
          description: 'Daha hizli kesim temposu.',
          iconKey: 'double_knife',
          tier: 3,
          iconPath: 'assets/ui/upgrades/knife/double_knife.png',
          baseCost: 18000,
          costMultiplier: 1.24,
          baseEffect: 7.80,
          levelEffect: 0.35,
        ),
        UpgradeItemTier(
          id: 'electric_knife',
          name: 'Elektrikli Bicak',
          description: 'Modern ekipmanla seri kesim.',
          iconKey: 'electric_knife',
          tier: 4,
          iconPath: 'assets/ui/upgrades/knife/electric_knife.png',
          baseCost: 650000,
          costMultiplier: 1.25,
          baseEffect: 18.00,
          levelEffect: 0.85,
        ),
        UpgradeItemTier(
          id: 'golden_knife',
          name: 'Altin Bicak',
          description: 'Premium hisli guclu kesim araci.',
          iconKey: 'golden_knife',
          tier: 5,
          iconPath: 'assets/ui/upgrades/knife/golden_knife.png',
          baseCost: 24000000,
          costMultiplier: 1.26,
          baseEffect: 42.00,
          levelEffect: 2.10,
        ),
        UpgradeItemTier(
          id: 'flaming_knife',
          name: 'Alevli Bicak',
          description: 'Guc patlamasi veren kesim ekipmani.',
          iconKey: 'flaming_knife',
          tier: 6,
          iconPath: 'assets/ui/upgrades/knife/flaming_knife.png',
          baseCost: 950000000,
          costMultiplier: 1.27,
          baseEffect: 100.00,
          levelEffect: 5.20,
        ),
        UpgradeItemTier(
          id: 'laser_knife',
          name: 'Lazer Bicak',
          description: 'Sci-fi hiz ve hassasiyet.',
          iconKey: 'laser_knife',
          tier: 7,
          iconPath: 'assets/ui/upgrades/knife/laser_knife.png',
          baseCost: 42000000000,
          costMultiplier: 1.28,
          baseEffect: 250.00,
          levelEffect: 13.00,
        ),
        UpgradeItemTier(
          id: 'doner_excalibur',
          name: 'Doner Excalibur',
          description: 'Efsanevi bicak kademesi.',
          iconKey: 'doner_excalibur',
          tier: 8,
          iconPath: 'assets/ui/upgrades/knife/doner_excalibur.png',
          baseCost: 2000000000000,
          costMultiplier: 1.29,
          baseEffect: 650.00,
          levelEffect: 35.00,
        ),
        UpgradeItemTier(
          id: 'master_sword',
          name: 'Ustanin Kilici',
          description: 'Prestige sonrasi guclu hedef.',
          iconKey: 'master_sword',
          tier: 9,
          iconPath: 'assets/ui/upgrades/knife/master_sword.png',
          baseCost: 110000000000000,
          costMultiplier: 1.30,
          baseEffect: 1800.00,
          levelEffect: 95.00,
        ),
        UpgradeItemTier(
          id: 'cosmic_doner_knife',
          name: 'Kozmik Doner Bicagi',
          description: 'Endgame kesim gucu.',
          iconKey: 'cosmic_doner_knife',
          tier: 10,
          iconPath: 'assets/ui/upgrades/knife/cosmic_doner_knife.png',
          baseCost: 7000000000000000,
          costMultiplier: 1.31,
          baseEffect: 5000.00,
          levelEffect: 280.00,
        ),
        UpgradeItemTier(
          id: 'galactic_cutter',
          name: 'Galaktik Kesici',
          description: 'Late endgame kesici.',
          iconKey: 'galactic_cutter',
          tier: 11,
          iconPath: 'assets/ui/upgrades/knife/galactic_cutter.png',
          baseCost: 500000000000000000,
          costMultiplier: 1.32,
          baseEffect: 15000.00,
          levelEffect: 850.00,
        ),
        UpgradeItemTier(
          id: 'infinite_knife',
          name: 'Sonsuz Bicak',
          description: 'Bicak track soft cap hedefi.',
          iconKey: 'infinite_knife',
          tier: 12,
          iconPath: 'assets/ui/upgrades/knife/infinite_knife.png',
          baseCost: 40000000000000000000,
          costMultiplier: 1.33,
          baseEffect: 50000.00,
          levelEffect: 3000.00,
        ),
      ],
    ),
    UpgradeTrack(
      id: 'staff',
      title: 'Personel',
      description: 'Oyuncu tiklamadan pasif gelir saglar.',
      type: UpgradeTrackType.staff,
      effectType: UpgradeEffectType.passiveIncome,
      itemIndex: 0,
      level: 1,
      tiers: [
        UpgradeItemTier(
          id: 'apprentice',
          name: 'Cirak',
          description: 'Ilk yardimci personel.',
          iconKey: 'apprentice',
          tier: 1,
          iconPath: 'assets/ui/upgrades/staff/apprentice.png',
          baseCost: 100,
          costMultiplier: 1.22,
          baseEffect: 1,
          levelEffect: 0.45,
        ),
        UpgradeItemTier(
          id: 'fast_apprentice',
          name: 'Hizli Cirak',
          description: 'Early boost saglayan yardimci.',
          iconKey: 'fast_apprentice',
          tier: 2,
          iconPath: 'assets/ui/upgrades/staff/fast_apprentice.png',
          baseCost: 2500,
          costMultiplier: 1.23,
          baseEffect: 18,
          levelEffect: 3.5,
        ),
        UpgradeItemTier(
          id: 'journeyman',
          name: 'Kalfa',
          description: 'Ilk ciddi pasif gelir kaynagi.',
          iconKey: 'journeyman',
          tier: 3,
          iconPath: 'assets/ui/upgrades/staff/journeyman.png',
          baseCost: 70000,
          costMultiplier: 1.24,
          baseEffect: 300,
          levelEffect: 60,
        ),
        UpgradeItemTier(
          id: 'assistant_master',
          name: 'Usta Yardimcisi',
          description: 'Orta seviye servis destegi.',
          iconKey: 'assistant_master',
          tier: 4,
          iconPath: 'assets/ui/upgrades/staff/assistant_master.png',
          baseCost: 2200000,
          costMultiplier: 1.25,
          baseEffect: 6000,
          levelEffect: 1200,
        ),
        UpgradeItemTier(
          id: 'doner_master',
          name: 'Doner Ustasi',
          description: 'Guclu pasif uretim.',
          iconKey: 'doner_master',
          tier: 5,
          iconPath: 'assets/ui/upgrades/staff/doner_master.png',
          baseCost: 90000000,
          costMultiplier: 1.26,
          baseEffect: 140000,
          levelEffect: 28000,
        ),
        UpgradeItemTier(
          id: 'head_master',
          name: 'Bas Usta',
          description: 'Dukkan hissini buyuten kademe.',
          iconKey: 'head_master',
          tier: 6,
          iconPath: 'assets/ui/upgrades/staff/head_master.png',
          baseCost: 4500000000,
          costMultiplier: 1.27,
          baseEffect: 3500000,
          levelEffect: 700000,
        ),
        UpgradeItemTier(
          id: 'chef',
          name: 'Sef',
          description: 'Restoran seviyesinde pasif uretim.',
          iconKey: 'chef',
          tier: 7,
          iconPath: 'assets/ui/upgrades/staff/chef.png',
          baseCost: 260000000000,
          costMultiplier: 1.28,
          baseEffect: 90000000,
          levelEffect: 18000000,
        ),
        UpgradeItemTier(
          id: 'robot_staff',
          name: 'Robot Personel',
          description: 'Otomasyon destekli servis.',
          iconKey: 'robot_staff',
          tier: 8,
          iconPath: 'assets/ui/upgrades/staff/robot_staff.png',
          baseCost: 18000000000000,
          costMultiplier: 1.29,
          baseEffect: 2500000000,
          levelEffect: 500000000,
        ),
        UpgradeItemTier(
          id: 'ai_master',
          name: 'Yapay Zeka Ustasi',
          description: 'Sci-fi otomasyon ustasi.',
          iconKey: 'ai_master',
          tier: 9,
          iconPath: 'assets/ui/upgrades/staff/ai_master.png',
          baseCost: 1500000000000000,
          costMultiplier: 1.30,
          baseEffect: 75000000000,
          levelEffect: 15000000000,
        ),
        UpgradeItemTier(
          id: 'doner_army',
          name: 'Doner Ordusu',
          description: 'Endgame personel gucu.',
          iconKey: 'doner_army',
          tier: 10,
          iconPath: 'assets/ui/upgrades/staff/doner_army.png',
          baseCost: 140000000000000000,
          costMultiplier: 1.31,
          baseEffect: 2400000000000,
          levelEffect: 480000000000,
        ),
        UpgradeItemTier(
          id: 'franchise_team',
          name: 'Franchise Ekibi',
          description: 'Global servis ekibi.',
          iconKey: 'franchise_team',
          tier: 11,
          iconPath: 'assets/ui/upgrades/staff/franchise_team.png',
          baseCost: 15000000000000000000,
          costMultiplier: 1.32,
          baseEffect: 85000000000000,
          levelEffect: 17000000000000,
        ),
        UpgradeItemTier(
          id: 'infinite_masters',
          name: 'Sonsuz Ustalar',
          description: 'Personel track soft cap hedefi.',
          iconKey: 'infinite_masters',
          tier: 12,
          iconPath: 'assets/ui/upgrades/staff/infinite_masters.png',
          baseCost: 1800000000000000000000,
          costMultiplier: 1.33,
          baseEffect: 3200000000000000,
          levelEffect: 640000000000000,
        ),
      ],
    ),
    UpgradeTrack(
      id: 'oven',
      title: 'Ocak',
      description: 'Tap ve pasif dahil tum gelirleri artirir.',
      type: UpgradeTrackType.oven,
      effectType: UpgradeEffectType.globalIncomeMultiplier,
      itemIndex: 0,
      level: 1,
      tiers: [
        UpgradeItemTier(
          id: 'small_oven',
          name: 'Kucuk Ocak',
          description: 'Kompakt baslangic ocagi.',
          iconKey: 'small_oven',
          tier: 1,
          iconPath: 'assets/ui/upgrades/oven/small_oven.png',
          baseCost: 500,
          costMultiplier: 1.24,
          baseEffect: 1.00,
          levelEffect: 0.04,
        ),
        UpgradeItemTier(
          id: 'large_oven',
          name: 'Buyuk Ocak',
          description: 'Ilk dukkan buyumesi.',
          iconKey: 'large_oven',
          tier: 2,
          iconPath: 'assets/ui/upgrades/oven/large_oven.png',
          baseCost: 15000,
          costMultiplier: 1.25,
          baseEffect: 2.20,
          levelEffect: 0.08,
        ),
        UpgradeItemTier(
          id: 'double_oven',
          name: 'Cift Ocak',
          description: 'Kapasite artisi saglar.',
          iconKey: 'double_oven',
          tier: 3,
          iconPath: 'assets/ui/upgrades/oven/double_oven.png',
          baseCost: 500000,
          costMultiplier: 1.26,
          baseEffect: 4.80,
          levelEffect: 0.18,
        ),
        UpgradeItemTier(
          id: 'industrial_oven',
          name: 'Endustriyel Ocak',
          description: 'Fabrika hissi veren kademe.',
          iconKey: 'industrial_oven',
          tier: 4,
          iconPath: 'assets/ui/upgrades/oven/industrial_oven.png',
          baseCost: 22000000,
          costMultiplier: 1.27,
          baseEffect: 11.00,
          levelEffect: 0.45,
        ),
        UpgradeItemTier(
          id: 'robotic_oven',
          name: 'Robotik Ocak',
          description: 'Otomasyon destekli isi yonetimi.',
          iconKey: 'robotic_oven',
          tier: 5,
          iconPath: 'assets/ui/upgrades/oven/robotic_oven.png',
          baseCost: 1100000000,
          costMultiplier: 1.28,
          baseEffect: 27.00,
          levelEffect: 1.20,
        ),
        UpgradeItemTier(
          id: 'flame_reactor',
          name: 'Alev Reaktoru',
          description: 'Guc patlamasi veren ocak.',
          iconKey: 'flame_reactor',
          tier: 6,
          iconPath: 'assets/ui/upgrades/oven/flame_reactor.png',
          baseCost: 65000000000,
          costMultiplier: 1.29,
          baseEffect: 70.00,
          levelEffect: 3.20,
        ),
        UpgradeItemTier(
          id: 'laser_grill',
          name: 'Lazer Izgara',
          description: 'Sci-fi izgara sistemi.',
          iconKey: 'laser_grill',
          tier: 7,
          iconPath: 'assets/ui/upgrades/oven/laser_grill.png',
          baseCost: 4200000000000,
          costMultiplier: 1.30,
          baseEffect: 190.00,
          levelEffect: 9.00,
        ),
        UpgradeItemTier(
          id: 'space_oven_system',
          name: 'Uzay Ocak Sistemi',
          description: 'Endgame ocak sistemi.',
          iconKey: 'space_oven_system',
          tier: 8,
          iconPath: 'assets/ui/upgrades/oven/space_oven_system.png',
          baseCost: 320000000000000,
          costMultiplier: 1.31,
          baseEffect: 550.00,
          levelEffect: 28.00,
        ),
        UpgradeItemTier(
          id: 'galactic_oven',
          name: 'Galaktik Firin',
          description: 'Late endgame global carpan.',
          iconKey: 'galactic_oven',
          tier: 9,
          iconPath: 'assets/ui/upgrades/oven/galactic_oven.png',
          baseCost: 28000000000000000,
          costMultiplier: 1.32,
          baseEffect: 1700.00,
          levelEffect: 90.00,
        ),
        UpgradeItemTier(
          id: 'infinite_heat_core',
          name: 'Sonsuz Isi Cekirdegi',
          description: 'Ocak track soft cap hedefi.',
          iconKey: 'infinite_heat_core',
          tier: 10,
          iconPath: 'assets/ui/upgrades/oven/infinite_heat_core.png',
          baseCost: 3000000000000000000,
          costMultiplier: 1.33,
          baseEffect: 5500.00,
          levelEffect: 300.00,
        ),
      ],
    ),
    UpgradeTrack(
      id: 'menu',
      title: 'Menu',
      description: 'Tum gelire kalite carpani verir.',
      type: UpgradeTrackType.menu,
      effectType: UpgradeEffectType.menuMultiplier,
      itemIndex: 0,
      level: 1,
      tiers: [
        UpgradeItemTier(
          id: 'chicken_doner',
          name: 'Tavuk Doner',
          description: 'Temel menu secenegi.',
          iconKey: 'chicken_doner',
          tier: 1,
          iconPath: 'assets/ui/upgrades/menu/chicken_doner.png',
          baseCost: 1000,
          costMultiplier: 1.23,
          baseEffect: 1.00,
          levelEffect: 0.035,
        ),
        UpgradeItemTier(
          id: 'beef_doner',
          name: 'Et Doner',
          description: 'Klasik gelisim menusu.',
          iconKey: 'beef_doner',
          tier: 2,
          iconPath: 'assets/ui/upgrades/menu/beef_doner.png',
          baseCost: 28000,
          costMultiplier: 1.24,
          baseEffect: 1.90,
          levelEffect: 0.075,
        ),
        UpgradeItemTier(
          id: 'hatay_style',
          name: 'Hatay Usulu',
          description: 'Lezzet acilimi saglar.',
          iconKey: 'hatay_style',
          tier: 3,
          iconPath: 'assets/ui/upgrades/menu/hatay_style.png',
          baseCost: 900000,
          costMultiplier: 1.25,
          baseEffect: 4.00,
          levelEffect: 0.17,
        ),
        UpgradeItemTier(
          id: 'sauced_doner',
          name: 'Soslu Doner',
          description: 'Dopaminli menu temasi.',
          iconKey: 'sauced_doner',
          tier: 4,
          iconPath: 'assets/ui/upgrades/menu/sauced_doner.png',
          baseCost: 36000000,
          costMultiplier: 1.26,
          baseEffect: 9.50,
          levelEffect: 0.42,
        ),
        UpgradeItemTier(
          id: 'gourmet_doner',
          name: 'Gurme Doner',
          description: 'Restoran hissi veren menu.',
          iconKey: 'gourmet_doner',
          tier: 5,
          iconPath: 'assets/ui/upgrades/menu/gourmet_doner.png',
          baseCost: 1700000000,
          costMultiplier: 1.27,
          baseEffect: 24.00,
          levelEffect: 1.10,
        ),
        UpgradeItemTier(
          id: 'golden_doner',
          name: 'Altin Doner',
          description: 'Premium menu hissi.',
          iconKey: 'golden_doner',
          tier: 6,
          iconPath: 'assets/ui/upgrades/menu/golden_doner.png',
          baseCost: 95000000000,
          costMultiplier: 1.28,
          baseEffect: 62.00,
          levelEffect: 3.00,
        ),
        UpgradeItemTier(
          id: 'legendary_sauce_doner',
          name: 'Efsane Soslu Doner',
          description: 'Mid/endgame lezzet hedefi.',
          iconKey: 'legendary_sauce_doner',
          tier: 7,
          iconPath: 'assets/ui/upgrades/menu/legendary_sauce_doner.png',
          baseCost: 6200000000000,
          costMultiplier: 1.29,
          baseEffect: 170.00,
          levelEffect: 8.50,
        ),
        UpgradeItemTier(
          id: 'king_wrap',
          name: 'Kral Durum',
          description: 'Eglenceli ust menu kademesi.',
          iconKey: 'king_wrap',
          tier: 8,
          iconPath: 'assets/ui/upgrades/menu/king_wrap.png',
          baseCost: 480000000000000,
          costMultiplier: 1.30,
          baseEffect: 500.00,
          levelEffect: 26.00,
        ),
        UpgradeItemTier(
          id: 'cosmic_doner',
          name: 'Kozmik Doner',
          description: 'Sci-fi menu carpani.',
          iconKey: 'cosmic_doner',
          tier: 9,
          iconPath: 'assets/ui/upgrades/menu/cosmic_doner.png',
          baseCost: 42000000000000000,
          costMultiplier: 1.31,
          baseEffect: 1550.00,
          levelEffect: 85.00,
        ),
        UpgradeItemTier(
          id: 'universe_doner',
          name: 'Evrenin Doneri',
          description: 'Menu track soft cap hedefi.',
          iconKey: 'universe_doner',
          tier: 10,
          iconPath: 'assets/ui/upgrades/menu/universe_doner.png',
          baseCost: 4500000000000000000,
          costMultiplier: 1.32,
          baseEffect: 5200.00,
          levelEffect: 300.00,
        ),
      ],
    ),
    UpgradeTrack(
      id: 'turbo',
      title: 'Turbo',
      description: 'Turbo mode aktifken click multiplier degerini artirir.',
      type: UpgradeTrackType.turbo,
      effectType: UpgradeEffectType.turboMultiplier,
      itemIndex: 0,
      level: 1,
      tiers: [
        UpgradeItemTier(
          id: 'turbo_cut',
          name: 'Turbo Kesim',
          description: 'Baslangic turbo kesimi.',
          iconKey: 'turbo_cut',
          tier: 1,
          iconPath: 'assets/ui/upgrades/turbo/turbo_cut.png',
          baseCost: 750,
          costMultiplier: 1.24,
          baseEffect: 3.00,
          levelEffect: 0.12,
        ),
        UpgradeItemTier(
          id: 'fast_cut',
          name: 'Hizli Kesim',
          description: 'Early boost turbo kademesi.',
          iconKey: 'fast_cut',
          tier: 2,
          iconPath: 'assets/ui/upgrades/turbo/fast_cut.png',
          baseCost: 22000,
          costMultiplier: 1.25,
          baseEffect: 7.00,
          levelEffect: 0.28,
        ),
        UpgradeItemTier(
          id: 'flaming_turbo',
          name: 'Alevli Turbo',
          description: 'Gorsel guc veren turbo.',
          iconKey: 'flaming_turbo',
          tier: 3,
          iconPath: 'assets/ui/upgrades/turbo/flaming_turbo.png',
          baseCost: 750000,
          costMultiplier: 1.26,
          baseEffect: 16.00,
          levelEffect: 0.70,
        ),
        UpgradeItemTier(
          id: 'master_mode',
          name: 'Usta Modu',
          description: 'Midgame aktif oyun kademesi.',
          iconKey: 'master_mode',
          tier: 4,
          iconPath: 'assets/ui/upgrades/turbo/master_mode.png',
          baseCost: 32000000,
          costMultiplier: 1.27,
          baseEffect: 40.00,
          levelEffect: 1.80,
        ),
        UpgradeItemTier(
          id: 'doner_storm',
          name: 'Doner Firtinasi',
          description: 'Dopaminli turbo hedefi.',
          iconKey: 'doner_storm',
          tier: 5,
          iconPath: 'assets/ui/upgrades/turbo/doner_storm.png',
          baseCost: 1600000000,
          costMultiplier: 1.28,
          baseEffect: 105.00,
          levelEffect: 5.00,
        ),
        UpgradeItemTier(
          id: 'apocalypse_cut',
          name: 'Kiyamet Kesimi',
          description: 'Endgame hissi veren turbo.',
          iconKey: 'apocalypse_cut',
          tier: 6,
          iconPath: 'assets/ui/upgrades/turbo/apocalypse_cut.png',
          baseCost: 95000000000,
          costMultiplier: 1.29,
          baseEffect: 290.00,
          levelEffect: 14.00,
        ),
        UpgradeItemTier(
          id: 'light_speed_cut',
          name: 'Isik Hizi Kesim',
          description: 'Sci-fi aktif oynanis hedefi.',
          iconKey: 'light_speed_cut',
          tier: 7,
          iconPath: 'assets/ui/upgrades/turbo/light_speed_cut.png',
          baseCost: 6500000000000,
          costMultiplier: 1.30,
          baseEffect: 850.00,
          levelEffect: 45.00,
        ),
        UpgradeItemTier(
          id: 'cosmic_turbo',
          name: 'Kozmik Turbo',
          description: 'Late endgame turbo carpani.',
          iconKey: 'cosmic_turbo',
          tier: 8,
          iconPath: 'assets/ui/upgrades/turbo/cosmic_turbo.png',
          baseCost: 520000000000000,
          costMultiplier: 1.31,
          baseEffect: 2700.00,
          levelEffect: 150.00,
        ),
        UpgradeItemTier(
          id: 'infinite_turbo',
          name: 'Sonsuz Turbo',
          description: 'Turbo track soft cap hedefi.',
          iconKey: 'infinite_turbo',
          tier: 9,
          iconPath: 'assets/ui/upgrades/turbo/infinite_turbo.png',
          baseCost: 48000000000000000,
          costMultiplier: 1.32,
          baseEffect: 9000.00,
          levelEffect: 520.00,
        ),
      ],
    ),
    UpgradeTrack(
      id: 'offline',
      title: 'Offline',
      description: 'Offline earning efficiency degerini gelistirir.',
      type: UpgradeTrackType.offline,
      effectType: UpgradeEffectType.offlineEfficiency,
      itemIndex: 0,
      level: 1,
      tiers: [
        UpgradeItemTier(
          id: 'small_safe',
          name: 'Kucuk Kasa',
          description: 'Baslangic offline kazanc korumasi.',
          iconKey: 'small_safe',
          tier: 1,
          iconPath: 'assets/ui/upgrades/offline/small_safe.png',
          baseCost: 2000,
          costMultiplier: 1.23,
          baseEffect: 0.20,
          levelEffect: 0.008,
        ),
        UpgradeItemTier(
          id: 'secure_safe',
          name: 'Guvenli Kasa',
          description: 'Daha guvenli offline birikim.',
          iconKey: 'secure_safe',
          tier: 2,
          iconPath: 'assets/ui/upgrades/offline/secure_safe.png',
          baseCost: 70000,
          costMultiplier: 1.24,
          baseEffect: 0.45,
          levelEffect: 0.010,
        ),
        UpgradeItemTier(
          id: 'smart_safe',
          name: 'Akilli Kasa',
          description: 'Otomasyon destekli kasa.',
          iconKey: 'smart_safe',
          tier: 3,
          iconPath: 'assets/ui/upgrades/offline/smart_safe.png',
          baseCost: 2800000,
          costMultiplier: 1.25,
          baseEffect: 0.75,
          levelEffect: 0.012,
        ),
        UpgradeItemTier(
          id: 'big_storage',
          name: 'Buyuk Depo',
          description: 'Offline kapasite hissi.',
          iconKey: 'big_storage',
          tier: 4,
          iconPath: 'assets/ui/upgrades/offline/big_storage.png',
          baseCost: 130000000,
          costMultiplier: 1.26,
          baseEffect: 1.10,
          levelEffect: 0.014,
        ),
        UpgradeItemTier(
          id: 'night_shift',
          name: 'Gece Vardiyasi',
          description: 'Personel baglantili offline kazanc.',
          iconKey: 'night_shift',
          tier: 5,
          iconPath: 'assets/ui/upgrades/offline/night_shift.png',
          baseCost: 7000000000,
          costMultiplier: 1.27,
          baseEffect: 1.50,
          levelEffect: 0.016,
        ),
        UpgradeItemTier(
          id: 'franchise_system',
          name: 'Franchise Sistemi',
          description: 'Global offline gelir sistemi.',
          iconKey: 'franchise_system',
          tier: 6,
          iconPath: 'assets/ui/upgrades/offline/franchise_system.png',
          baseCost: 420000000000,
          costMultiplier: 1.28,
          baseEffect: 2.00,
          levelEffect: 0.020,
        ),
        UpgradeItemTier(
          id: 'auto_branch_network',
          name: 'Otomatik Sube Agi',
          description: 'Endgame offline agi.',
          iconKey: 'auto_branch_network',
          tier: 7,
          iconPath: 'assets/ui/upgrades/offline/auto_branch_network.png',
          baseCost: 30000000000000,
          costMultiplier: 1.29,
          baseEffect: 2.60,
          levelEffect: 0.026,
        ),
        UpgradeItemTier(
          id: 'global_doner_network',
          name: 'Global Doner Agi',
          description: 'Late endgame offline hedefi.',
          iconKey: 'global_doner_network',
          tier: 8,
          iconPath: 'assets/ui/upgrades/offline/global_doner_network.png',
          baseCost: 2500000000000000,
          costMultiplier: 1.30,
          baseEffect: 3.40,
          levelEffect: 0.034,
        ),
        UpgradeItemTier(
          id: 'infinite_safe_system',
          name: 'Sonsuz Kasa Sistemi',
          description: 'Offline track soft cap hedefi.',
          iconKey: 'infinite_safe_system',
          tier: 9,
          iconPath: 'assets/ui/upgrades/offline/infinite_safe_system.png',
          baseCost: 240000000000000000,
          costMultiplier: 1.31,
          baseEffect: 4.50,
          levelEffect: 0.045,
        ),
      ],
    ),
  ];

  static final Map<String, UpgradeTrack> byId =
      Map<String, UpgradeTrack>.unmodifiable({
        for (final track in tracks) track.id: track,
      });

  static UpgradeTrack? maybeTrack(String id) {
    return byId[id];
  }

  static UpgradeTrack track(String id) {
    final track = maybeTrack(id);
    if (track == null) {
      throw ArgumentError.value(id, 'id', 'Unknown upgrade track id.');
    }
    return track;
  }
}

List<UpgradeTrack> defaultUpgradeTracks() {
  return List<UpgradeTrack>.unmodifiable(UpgradeDefinitions.tracks);
}

Map<String, UpgradeTrack> defaultUpgradeTrackMap() {
  return Map<String, UpgradeTrack>.unmodifiable(UpgradeDefinitions.byId);
}
